name: Deploy to ECS Cluster

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Install AWS CLI
      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli

      # Initialize Terraform
      - name: Initialize Terraform
        working-directory: ./terraform   # Change to the Terraform directory
        run: terraform init

      # Apply Terraform changes
      - name: Apply Terraform changes
        working-directory: ./terraform   # Change to the Terraform directory
        run: terraform apply -auto-approve
        
      - name: Retrieve ECR repository URL
        id: ecr
        working-directory: ./terraform   # Change to the Terraform directory
        run: |
          ecr_repo_url=$(terraform output -raw ecr_repo_url)
          echo "ECR_REPO_URL=${ecr_repo_url}" >> $GITHUB_ENV

      # Build Docker image
      - name: Build Docker image
        run: |
          docker build -t ${{ steps.ecr.outputs.ecr_repo_url }} .
      
      # Tag Docker image with ECR repository URL
      - name: Tag Docker image
        run: |
          docker tag my-image ${{ steps.ecr.outputs.ecr_repo_url }}

      # Push Docker image to ECR
      - name: Push Docker image to Amazon ECR
        run: |
          docker push ${{ steps.ecr.outputs.ecr_repo_url }}
 
      - name: Update ECS service
        run: |
          aws ecs update-service --cluster $(terraform output -raw ecs_cluster_name) --service $(terraform output -raw ecs_service_name) --force-new-deployment
